# 向量水果店


## 1. 基于向量的表示方法



In [1]:
import numpy as np

价格向量

In [2]:
p = np.array([2, 3])
p

array([2, 3])

<br>

采购数量向量

In [3]:
a = np.array([70, 80])
a

array([70, 80])

In [4]:
p @ a

380

In [5]:
p * a

array([140, 240])

In [6]:
(p * a).sum()

380

## 2. 基于矩阵的表示方法

如果客户这个订单是实际要分3个批次采购：
* 第1个批次： 苹果20，香蕉40
* 第2个批次： 苹果35，香蕉15
* 第3个批次： 苹果15，香蕉25


<br>
采购批次矩阵：

In [7]:
A = np.array([[20, 40], [35, 15], [15, 25]]) 
A

array([[20, 40],
       [35, 15],
       [15, 25]])

In [8]:
A @ p

array([160, 115, 105])

In [9]:
p @ A.T

array([160, 115, 105])

In [10]:
(A @ p).sum()

380

In [11]:
(p @ A.T).sum()

380

## 价格方案

在实际执行时，价格上是有两个等级折扣：
* 第一等级$1\%$的折扣
* 第二等级$3\%$的折扣。

$$
实际价格 = (1 - 折扣) \cdot  价格 
$$

三种折扣方案：不打折，打折$2\%$，打折$3\%$

In [20]:
d = 1 - np.array([0, 0.02, 0.03])
d

array([1.  , 0.98, 0.97])

<br>

三种折扣方案针对苹果和香蕉的折扣方案

In [21]:
P = np.outer(d, p)
P

array([[2.  , 3.  ],
       [1.96, 2.94],
       [1.94, 2.91]])

In [23]:
d.reshape(-1,1) @  p.reshape(-1, 1).T

array([[2.  , 3.  ],
       [1.96, 2.94],
       [1.94, 2.91]])

<br>

如果针对该订单3批采购，分别执行这个三个价格方案

In [15]:
X = P @ A.T
X

array([[160.  , 115.  , 105.  ],
       [156.8 , 112.7 , 102.9 ],
       [155.2 , 111.55, 101.85]])

<br>

三个价格方案的总计收入：

In [24]:
X.sum(axis=1)

array([380. , 372.4, 368.6])

<br>

矩阵对角线是什么含义？（第4个价格方案）

In [25]:
np.diag(X)

array([160.  , 112.7 , 101.85])

In [26]:
np.diag(X).sum()

374.54999999999995