# 向量水果店


## 1. 基于向量的表示方法



In [2]:
2 * 70 + 3 * 80

380

In [5]:
import numpy as np

In [6]:
np.array(2) * np.array(70)

140

价格向量

In [7]:
p = np.array([2, 3])
p

array([2, 3])

<br>

采购数量向量

In [8]:
a = np.array([70, 80])
a

array([70, 80])

$$
p \cdot a = (p_1, p_2,\dots, p_n) \cdot (a_1, a_2,\dots, a_n)
=\sum_{i=1}^n p_{i}* a_i
$$

In [10]:
p @ a

380

In [11]:
p = np.array([2])
a = np.array([70])

p @ a

140

In [12]:
p = np.array([2, 3])
a = np.array([70, 80])

p @ a

380

In [13]:
p = np.array([2, 3, 4])
a = np.array([70, 80, 90])

p @ a

740

In [15]:
p = np.array([2, 3])
a = np.array([70, 80])

p * a

array([140, 240])

In [16]:
(p * a).sum()

380

## 2. 基于矩阵的表示方法

如果客户这个订单是实际要分3个批次采购：
* 第1个批次： 苹果20，香蕉40
* 第2个批次： 苹果35，香蕉15
* 第3个批次： 苹果15，香蕉25


<br>
采购批次矩阵：

In [17]:
A = np.array([[20, 40], [35, 15], [15, 25]]) 
A

array([[20, 40],
       [35, 15],
       [15, 25]])

In [19]:
p = np.array([2, 3])

A @ p

array([160, 115, 105])

In [20]:
p @ A.T

array([160, 115, 105])

In [10]:
(A @ p).sum()

380

In [11]:
(p @ A.T).sum()

380

## 价格方案

在实际执行时，价格上是有两个等级折扣：
* 第一等级$2\%$的折扣
* 第二等级$3\%$的折扣。

$$
实际价格 = (1 - 折扣) \cdot  价格 
$$

三种折扣方案：不打折，打折$2\%$，打折$3\%$

In [25]:
d = 1 - np.array([0, 0.02, 0.03])
d

array([1.  , 0.98, 0.97])

<br>

三种折扣方案针对苹果和香蕉的折扣方案

In [31]:
P = np.outer(d, p)
P

array([[2.  , 3.  ],
       [1.96, 2.94],
       [1.94, 2.91]])

In [32]:
a = np.array([70, 80])

P @ a

array([380. , 372.4, 368.6])

In [33]:
a @ P.T

array([380. , 372.4, 368.6])

<br>

如果针对该订单3批采购，分别执行这个三个价格方案

In [36]:
A @ P.T

array([[160.  , 156.8 , 155.2 ],
       [115.  , 112.7 , 111.55],
       [105.  , 102.9 , 101.85]])

In [37]:
X = P @ A.T
X

array([[160.  , 115.  , 105.  ],
       [156.8 , 112.7 , 102.9 ],
       [155.2 , 111.55, 101.85]])

<br>

三个价格方案的总计收入：

In [24]:
X.sum(axis=1)

array([380. , 372.4, 368.6])

<br>

矩阵对角线是什么含义？（第4个价格方案）

In [25]:
np.diag(X)

array([160.  , 112.7 , 101.85])

In [26]:
np.diag(X).sum()

374.54999999999995

# 总结：信息“维度”

In [4]:
import numpy as np

### “点”

In [2]:
2 * 70

140

In [24]:
np.array(2) * np.array(70)

140

In [43]:
p = np.array([2])
a = np.array([70])

p @ a

140

### “线”

In [6]:
p = np.array([2, 3])
a = np.array([70, 80])

p @ a

380

### “面”
在向量$a$的基础上（各水果采购数量），增加“采购批次”信息（维度）

由1维信息（向量）变为2维信息（矩阵）

In [8]:
A = np.array([[20, 40], [35, 15], [15, 25]]) 
A

array([[20, 40],
       [35, 15],
       [15, 25]])

In [9]:
p = np.array([2, 3])

A @ p

array([160, 115, 105])

In [10]:
p @ A.T

array([160, 115, 105])

在采购价格向量$p$的基础上，增加的“价格方案”信息“维度”

与价格有关的信息由1维信息（向量）变为2维信息（矩阵）

In [12]:
d = 1 - np.array([0, 0.02, 0.03])
P = np.outer(d, p)
P

array([[2.  , 3.  ],
       [1.96, 2.94],
       [1.94, 2.91]])

In [41]:
P @ a

array([380. , 372.4, 368.6])

In [13]:
a @ P.T

array([380. , 372.4, 368.6])

In [15]:
P @ A.T

array([[160.  , 115.  , 105.  ],
       [156.8 , 112.7 , 102.9 ],
       [155.2 , 111.55, 101.85]])

In [18]:
A @ P.T

array([[160.  , 156.8 , 155.2 ],
       [115.  , 112.7 , 111.55],
       [105.  , 102.9 , 101.85]])

下面的计算就是没任何意义，因为“批次”信息和“价格”信息无直接“相互作用”，<br>
只能间接通过“采购价格”与“采购数量”信息维度相互作用，发生关系。

In [27]:
P

array([[2.  , 3.  ],
       [1.96, 2.94],
       [1.94, 2.91]])

In [20]:
A.T @ P

array([[137.7 , 206.55],
       [157.9 , 236.85]])

In [21]:
P.T @ A

array([[137.7 , 157.9 ],
       [206.55, 236.85]])