In [1]:
import numpy as np

In [6]:
np.pi

3.141592653589793

## 数组的形状

In [16]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
x.shape

(2, 3)

In [17]:
x = np.array([1, 2])
x.shape

(2,)

In [14]:
x = np.array([2,3])
x.shape

(2,)

In [19]:
x = np.array(10)
x.shape

()

## 数组形状调整，reshape

In [34]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
x.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [37]:
x = np.array([10, 20, 30])
x

array([10, 20, 30])

In [45]:
x.shape

(3,)

In [40]:
x1 = x.reshape(-1, 1)
x1

array([[10],
       [20],
       [30]])

In [41]:
x2 = x.reshape(1, -1)
x2

array([[10, 20, 30]])

In [44]:
print("x1 shape: ", x1.shape)
print("x2 shape: ", x2.shape)

x1 shape:  (3, 1)
x2 shape:  (1, 3)


In [52]:
x.reshape(2, 2)

ValueError: cannot reshape array of size 3 into shape (2,2)

## 数组广播

In [60]:
a = np.array([1, 2, 3])
x = np.array([[10, 20, 30],
              [40, 50, 60]])

x + a

array([[11, 22, 33],
       [41, 52, 63]])

In [62]:
a = np.array([1, 2])
x = np.array([[10, 20, 30],
              [40, 50, 60]])

x + a

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 