In [1]:
import numpy as np

In [6]:
np.pi

3.141592653589793

In [4]:
np.array(10)

array(10)

In [2]:
np.array([1,2, 3])

array([1, 2, 3])

In [3]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

## 数组的形状（shape）

In [5]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
x.shape

(2, 3)

In [17]:
x = np.array([1, 2])
x.shape

(2,)

In [6]:
x = np.array([2,3,4])
x.shape

(3,)

In [19]:
x = np.array(10)
x.shape

()

## 数组形状调整，reshape

In [9]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])

x.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
x = np.array([10, 20, 30, 40])
x

array([10, 20, 30, 40])

In [18]:
x = np.array(range(1, 9)) * 10
x

array([10, 20, 30, 40, 50, 60, 70, 80])

In [16]:
x = np.array(range(1, 9)) * 10
x.reshape(1, 8)

array([[10, 20, 30, 40, 50, 60, 70, 80]])

In [19]:
x = np.array(range(1, 9)) * 10
x.reshape(8, 1)

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80]])

In [20]:
x = np.array(range(1, 9)) * 10
x.reshape(2, 2, 2)

array([[[10, 20],
        [30, 40]],

       [[50, 60],
        [70, 80]]])

In [22]:
x = np.array(range(1, 9)) * 10
x.reshape(4, -1)

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [24]:
np.array(range(1, 9))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
A = np.array([1, 2, 3, 4]).reshape(2, -1)
A

array([[1, 2],
       [3, 4]])

In [28]:
x = np.array([10, 20])

In [31]:
x @ x

500

In [29]:
A @ x

array([ 50, 110])

In [30]:
x @ A

array([ 70, 100])

In [38]:
x.reshape(1, -1) @ A

array([[ 70, 100]])

In [39]:
A @ x.reshape(1, -1)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

In [41]:
A @ x.reshape(-1, 1)

array([[ 50],
       [110]])

In [42]:
x.reshape(-1, 1) @ A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [23]:
x = np.array(range(1, 9)) * 10
x.reshape(1, -1)

array([[10, 20, 30, 40, 50, 60, 70, 80]])

In [45]:
x.shape

(3,)

In [3]:
x1 = x.reshape(-1, 1)
x1

array([[10],
       [20],
       [30]])

In [4]:
x2 = x.reshape(1, -1)
x2

array([[10, 20, 30]])

In [5]:
x1 @ x2

array([[100, 200, 300],
       [200, 400, 600],
       [300, 600, 900]])

In [44]:
print("x1 shape: ", x1.shape)
print("x2 shape: ", x2.shape)

x1 shape:  (3, 1)
x2 shape:  (1, 3)


In [52]:
x.reshape(2, 2)

ValueError: cannot reshape array of size 3 into shape (2,2)

## 数组广播

In [43]:
1 + np.array([10, 20, 30])

array([11, 21, 31])

In [44]:
np.array(1) + np.array([10, 20, 30])

array([11, 21, 31])

In [45]:
np.array([1, 1, 1]) + np.array([10, 20, 30])

array([11, 21, 31])

In [47]:
a = np.array([1, 2, 3])
x = np.array([[10, 20, 30],
              [40, 50, 60]])

x + a

array([[11, 22, 33],
       [41, 52, 63]])

In [49]:
np.array([[1, 2, 3], [1, 2, 3]]) + x

array([[11, 22, 33],
       [41, 52, 63]])

In [50]:
a = np.array([1, 2])
x = np.array([[10, 20, 30],
              [40, 50, 60]])

x + a

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [11]:
np.array(100).shape

()

In [9]:
x = np.array([[10, 20, 30],
              [40, 50, 60]]) 

x + np.array(100)

array([[110, 120, 130],
       [140, 150, 160]])