In [2]:
import numpy as np

In [4]:
[10, 20, 30] * 3

[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [5]:
np.array([10, 20, 30]) * 3

array([30, 60, 90])

### 一阶数组的访问方式

In [6]:
x = np.array([10, 20, 30, 40, 50, 60])
x

array([10, 20, 30, 40, 50, 60])

In [7]:
x[0]

10

In [8]:
x[-1]

60

In [12]:
x[2:5]

array([30, 40, 50])

In [13]:
x[::-1]

array([60, 50, 40, 30, 20, 10])

### 花式下标访问

In [14]:
x = np.array([10, 20, 30, 40, 50, 60])
x

array([10, 20, 30, 40, 50, 60])

In [15]:
x[[2, 3, 0]]

array([30, 40, 10])

In [24]:
x = np.array([10, 20, 30, 40, 50, 60])
x[[1]]

array([20])

In [23]:
x[1]

20

## 布尔向量

In [25]:
x = np.array([10, 20, 30, 40, 50, 60])
x

array([10, 20, 30, 40, 50, 60])

In [26]:
x > 20

array([False, False,  True,  True,  True,  True])

In [27]:
x < 50

array([ True,  True,  True,  True, False, False])

In [7]:
(x > 20) & (x < 50)

array([False, False,  True,  True, False, False])

In [29]:
(x < 20) | (x > 50)

array([ True, False, False, False, False,  True])

In [31]:
x > 20 & x < 50

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [33]:
x > 20 & (x < 50)

array([ True,  True,  True,  True,  True,  True])

In [34]:
(x > 20) & x < 50

array([ True,  True,  True,  True,  True,  True])

In [35]:
(x > 20) & (x < 50)

array([False, False,  True,  True, False, False])

In [36]:
x[(x > 20) & (x < 50)]

array([30, 40])

In [37]:
x = np.arange(1, 25).reshape(-1, 6)
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [39]:
x[2, 3].shape

()

In [42]:
x[:, 3]

array([ 4, 10, 16, 22])

In [44]:
x[:, [3]]

array([[ 4],
       [10],
       [16],
       [22]])

In [28]:
x[:, 3:4]

array([[ 4],
       [10],
       [16],
       [22]])

In [29]:
x[:2, 3:4]

array([[ 4],
       [10]])

In [31]:
x[:2]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [45]:
x[:2, :]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [32]:
x[2, :]

array([13, 14, 15, 16, 17, 18])

In [55]:
x[2]

array([13, 14, 15, 16, 17, 18])

In [46]:
x[[2]]

array([[13, 14, 15, 16, 17, 18]])

In [60]:
x[0:3, :3]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]])

In [61]:
x[::-1, ::-1]

array([[24, 23, 22, 21, 20, 19],
       [18, 17, 16, 15, 14, 13],
       [12, 11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2,  1]])

In [33]:
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [47]:
x % 4 == 0

array([[False, False, False,  True, False, False],
       [False,  True, False, False, False,  True],
       [False, False, False,  True, False, False],
       [False,  True, False, False, False,  True]])

In [34]:
x[x % 4 == 0]

array([ 4,  8, 12, 16, 20, 24])

## 索引赋值

In [49]:
x = np.arange(1, 25).reshape(-1, 6)
x[0:3, 0:3] = 0
x

array([[ 0,  0,  0,  4,  5,  6],
       [ 0,  0,  0, 10, 11, 12],
       [ 0,  0,  0, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [51]:
x = np.arange(1, 25).reshape(-1, 6)
x[x <= 12] = 0
x

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [53]:
x = np.arange(1, 25).reshape(-1, 6)
x[x % 4 == 0] = 0
x

array([[ 1,  2,  3,  0,  5,  6],
       [ 7,  0,  9, 10, 11,  0],
       [13, 14, 15,  0, 17, 18],
       [19,  0, 21, 22, 23,  0]])