In [2]:
import numpy as np

In [3]:
x = np.arange(1, 25).reshape(4, -1)
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [5]:
x.sum()

300

In [7]:
x.shape

(4, 6)

In [6]:
x.sum(axis=0)

array([40, 44, 48, 52, 56, 60])

In [7]:
x.sum(axis=1)

array([ 21,  57,  93, 129])

In [10]:
x.sum(axis=(0, 1))

300

In [10]:
x = np.arange(1, 25).reshape(4, 2, -1)
x

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [11]:
x.sum(axis=(1,2))

array([ 21,  57,  93, 129])

In [12]:
scores = np.array([85, 92, np.nan, 78, 90])
scores

array([85., 92., nan, 78., 90.])

In [14]:
np.isnan(scores)

array([False, False,  True, False, False])

In [16]:
np.isnan(scores).any()

True

In [12]:
scores = np.array([85, 92, 61, 78, 90])
scores

array([85, 92, 61, 78, 90])

In [16]:
(scores >= 60).all()

True