In [2]:
import numpy as np


## 1. 矩阵的转置(Transpose)

In [5]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [7]:
x.T

array([[1, 3],
       [2, 4]])

### 3.3.2. 矩阵行列式(Determinant)

In [8]:
A = np.array([[1, 2], [3, 4]])
np.linalg.det(A)

-2.0000000000000004

<br>

### 3.3.3.  矩阵的逆(Inverse)

In [9]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [10]:
A_inv = np.linalg.inv(A)
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [11]:
A @ A_inv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [12]:
A_inv @ A

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

<br>

## 方程组求解

In [143]:
A = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])

display(A); display(b)

array([[1, 2],
       [3, 5]])

array([1, 2])

In [144]:
x = np.linalg.solve(A, b)
x

array([-1.,  1.])

In [139]:
A @ x - b

array([-1.11022302e-16,  0.00000000e+00])

In [140]:
np.allclose(A @ x, b)

True

In [15]:
A = np.array([[1, 2], [3, 4]])
I = np.diag([1, 1])

In [16]:
A_inv = np.linalg.solve(A, I)
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [150]:
A @ A_inv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [151]:
np.allclose(A @ A_inv, I)

True

<br>

### 3.3.5.  特征值（eigen values）、特征向量(eigen vectors)

In [76]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
w, v = np.linalg.eig(A)

print(f"w:\n{w}")
print(f"v:\n{v}")

w:
[-0.37228132  5.37228132]
v:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [86]:
v @ np.diag(w) @ np.linalg.inv(v)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

<br>
对角阵的特征值

In [23]:
A = np.diag([1, 2, 3])
A

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [24]:
w, v = np.linalg.eig(A)

print(f"w:\n{w}")
print(f"v:\n{v}")

w:
[1. 2. 3.]
v:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
