In [1]:
import numpy as np


## 1. 矩阵的转置(Transpose)

In [2]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [3]:
x.T

array([[1, 3],
       [2, 4]])

### 3.3.2. 矩阵行列式(Determinant)

In [4]:
A = np.array([[1, 2], [3, 4]])
np.linalg.det(A)

-2.0000000000000004

<br>

### 3.3.3.  矩阵的逆(Inverse)

In [5]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [6]:
A_inv = np.linalg.inv(A)
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [7]:
A @ A_inv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [8]:
A_inv @ A

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

In [9]:
I = np.diag([1, 1])

In [10]:
np.allclose(A_inv @ A, I)

True

In [11]:
np.allclose(A @ A_inv , I)

True

<br>

## 方程组求解

In [12]:
A = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])

display(A); display(b)

array([[1, 2],
       [3, 5]])

array([1, 2])

In [13]:
x = np.linalg.solve(A, b)
x

array([-1.,  1.])

In [14]:
A @ x - b

array([-1.11022302e-16,  0.00000000e+00])

In [15]:
np.allclose(A @ x, b)

True

In [16]:
A = np.array([[1, 2], [3, 4]])
I = np.diag([1, 1])

In [17]:
A_inv = np.linalg.solve(A, I)
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [18]:
A @ A_inv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [19]:
np.allclose(A @ A_inv, I)

True

<br>

### 3.3.5.  特征值（eigen values）、特征向量(eigen vectors)

$$
A x = \lambda x
$$

In [20]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

$$
\begin{cases}
A  x_1 &= \lambda_1 \cdot x_1   \\ 
A  x_2 &= \lambda_2 \cdot x_2 \\
A  x_3 &= \lambda_3 \cdot x_3
\end{cases}
$$


In [21]:
w, x = np.linalg.eig(A)

print(f"特征值的向量 w:\n{w}")
print(f"\n特征向量矩阵 x:\n{x}")

特征值的向量 w:
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]

特征向量矩阵 x:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


特征值从大到小排列，第$i$个特征值 `w[i]` 对应的特征向量是 `v[:, i]`

$$
X = \begin{pmatrix}
    \vert & \vert & \vert \\
    x_1   & x_2   & x_3 \\
    \vert & \vert & \vert \\
\end{pmatrix}
$$

$$
A X = X \Lambda = 
\begin{pmatrix}
    \vert & \vert & \vert \\
    x_1   & x_2   & x_3 \\
    \vert & \vert & \vert \\
\end{pmatrix}
\begin{pmatrix}
\lambda_1 & & \\
& \lambda_2 & \\
& & \lambda_3 \\
\end{pmatrix}
$$

In [22]:
A @ x[:, 0] - w[0] * x[:, 0]

array([ 5.32907052e-15, -1.77635684e-15, -1.77635684e-15])

In [23]:
[np.allclose(A @ x[:, i],  w[i] * x[:, i]) for i in range(3)]

[True, True, True]

$$
A X =  X \Lambda
$$

In [24]:
A @ x - x @ np.diag(w)

array([[ 5.32907052e-15, -3.33066907e-16, -3.55954217e-16],
       [-1.77635684e-15, -9.57567359e-16, -1.95262683e-15],
       [-1.77635684e-15, -2.77555756e-15,  5.32224203e-16]])

In [25]:
A @ x - w * x

array([[ 5.32907052e-15, -3.33066907e-16, -3.55954217e-16],
       [-1.77635684e-15, -9.57567359e-16, -1.95262683e-15],
       [-1.77635684e-15, -2.77555756e-15,  5.32224203e-16]])

注意：上面算式中的`@`和`*`运算含义区别

$$
A X =  X \Lambda
$$

A可以分解成特征值和特征向量

$$
A = X \Lambda X^{-1}
$$

In [26]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
w, x = np.linalg.eig(A)

In [28]:
A1 = x @ np.diag(w) @ np.linalg.inv(x)
A1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [29]:
A1 - A

array([[ 2.44249065e-15,  2.22044605e-15,  3.99680289e-15],
       [-8.88178420e-16, -2.66453526e-15,  0.00000000e+00],
       [-1.77635684e-15, -1.77635684e-15,  0.00000000e+00]])

观察到第三个特征 `-1.30367773e-15` 是一个非常小的值，说明对应的第三个特征向量的提供的“信息”作用不大

尝试第三个特征向量，使用前两个重新构造矩阵

In [30]:
print("前2个特征值对角阵: ")
display(np.diag(w[0:2]))

print("\n前2个特征向量: ")
display(x[:,0:2])

前2个特征值对角阵: 


array([[16.11684397,  0.        ],
       [ 0.        , -1.11684397]])


前2个特征向量: 


array([[-0.23197069, -0.78583024],
       [-0.52532209, -0.08675134],
       [-0.8186735 ,  0.61232756]])

基于前2个特征值和特征向量重新构造（还原）出矩阵 `A`

In [31]:
A2 = x[:, 0:2] @ np.diag(w[0:2]) @ np.linalg.inv(x)[0:2]
A2

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [32]:
A2 - A

array([[ 2.66453526e-15,  1.77635684e-15,  3.99680289e-15],
       [-1.33226763e-15, -1.77635684e-15,  0.00000000e+00],
       [-1.77635684e-15, -1.77635684e-15,  0.00000000e+00]])

<br>

#### 对角阵的特征值

In [33]:
A = np.diag([1, 2, 3])
A

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [34]:
w, x = np.linalg.eig(A)

print(f"w:\n{w}")
print(f"\nx:\n{x}")

w:
[1. 2. 3.]

x:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
